#!/bin/bash

# This is a thin wrapper around kbc-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using kbc-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_KBCD

# Grab the value of $REAL_KBCCLI which may be kbc-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_KBCCLI}" "$@" | sed 's/\r//'
